import {createGame,act,settle} from './engine.mjs';import {buildView} from './views.mjs';import {loadGame,saveGame} from './storage.mjs';import {validateSnapshot} from './data.mjs';
const root=document.querySelector('#app');let s,g,tab='market',position='ALL',search='',preserveSave=false,savedGame=null,saveWarning='';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n===null?'待核实':n>=1000000?'$'+(n/1000000).toFixed(2)+'M':'$'+(n/1000).toFixed(0)+'K';
const exact=n=>'$'+Math.round(n).toLocaleString('en-US');const signed=n=>(n>=0?'+':'−')+money(Math.abs(n));const tone=n=>n>=0?'up':'down';
const playerName=id=>s.players.find(p=>p.id===id)?.name??id;
const initials=name=>name.split(' ').filter(Boolean).map(p=>p[0]).slice(0,2).join('');
const source=id=>s.sources.find(x=>x.id===id);let toastTimer;
function toast(message){const e=document.querySelector('#toast');e.textContent=message;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),3300);}
function persist(){if(preserveSave)return;let r;try{r=saveGame(localStorage,g);}catch{r={warning:'浏览器存储不可用，当前进度只能保留在本页。'};}saveWarning=r.warning??'';return r;}
function coverage(){const c=s.coverage,missing=c.missingSalaries.length;return `<p class="coverage">历史回放 · ${esc(s.season)}<br>${esc(s.startDate)} — ${esc(s.endDate)} · ${s.teams.length}队 / ${s.players.length}名球员</p><details><summary>数据来源与覆盖说明${missing?' · '+missing+'份合同待核实':''}</summary><p>阵容使用开季社区快照，并以历史战报交叉核对；尚未逐队完成官方全量核验。年薪采用 SalarySwish 的当赛季 Base Salary，区别于薪资帽占用。采集日期 ${esc(s.collectedAt.slice(0,10))}。新闻为精选事实，比赛结果按快照收录。</p><p>${missing?'缺失合同球员仍显示在名单，暂不能交易。':'当前名单的合同字段均有来源；仍需逐项交叉复核。'} <a href="./docs/data-sources.md" target="_blank" rel="noopener">完整说明</a></p></details>`;}
function setup(warning=''){
 root.innerHTML=`<section class="intro"><div><span class="eyebrow">30 DAYS. 30 TEAMS. YOUR CALL.</span><h1>下一站，<br>签下你的<span class="orange">机会。</span></h1><p>你是一名篮球经纪人。穿梭联盟，买入被低估的球员，将他们卖给愿意出价的球队。用30天证明你的眼光。</p><p class="muted">阅读真实比赛与新闻，判断价格变化。<br>市场不会告诉你每一站的答案。</p></div><section class="setup"><span class="eyebrow">YOUR FIRST DEAL STARTS HERE</span><h2>开启经纪人生涯</h2><div class="rules"><div><strong>1500<small>万</small></strong><span>初始资金 / 美元</span></div><div><strong>5<small>人</small></strong><span>仓库上限</span></div><div><strong>30<small>天</small></strong><span>经营期限</span></div></div><label for="start-team">选择第一站</label><select id="start-team">${s.teams.map(t=>`<option value="${esc(t.id)}" ${t.id==='13'?'selected':''}>${esc(t.name)} · ${esc(t.abbr)}</option>`).join('')}</select>${warning?`<div class="warning">${esc(warning)}</div>`:''}${savedGame?'<button class="primary" data-resume>继续上次生涯</button>':''}<button class="${savedGame?'':'primary'}" data-start style="width:100%;margin-top:12px">${savedGame?'重新开始':'开始交易 →'}</button>${coverage()}</section></section>`;
}
function header(v){return `<section class="hero"><div><span class="eyebrow">${esc(v.team.englishName.toUpperCase())}</span><h2>${esc(v.team.name)} · 球员市场</h2><p class="muted">${esc(v.date)} / 真实历史回放</p></div><div class="day"><strong>${g.day}<span> / 30</span></strong><div class="muted">经营日</div><div class="progress"><i style="width:${g.day/30*100}%"></i></div></div></section><div class="stats"><div class="stat"><label>可用资金 / USD</label><strong title="${exact(g.cash)}">${money(g.cash)}</strong></div><div class="stat"><label>已实现盈亏</label><strong class="${tone(g.realizedProfit)}">${signed(g.realizedProfit)}</strong></div><div class="stat"><label>球员仓库</label><strong>${g.holdings.length}<small> / 5 人</small></strong></div></div><nav class="tabs" aria-label="游戏页面">${[['market','当地市场'],['warehouse','我的仓库'],['map','前往球队'],['news','联盟资讯']].map(([id,label])=>`<button data-tab="${id}" class="${tab===id?'active':''}" aria-current="${tab===id?'page':'false'}">${label}${id==='warehouse'?`<small>${g.holdings.length}/5</small>`:''}</button>`).join('')}</nav>`;}
function playerCard(p,owned=false){const profit=p.price===null?null:p.price-p.cost;const delta=p.price===null?null:(p.price/p.salaryUsd-1)*100;
 return `<article class="card"><div class="player-top"><div class="avatar">${esc(initials(p.name))}</div><div class="player-info"><h3>${esc(p.name)}</h3><span class="pos">${p.position==='G'?'后卫':p.position==='C'?'中锋':'前锋'} / ${esc(p.position)}</span></div></div><div class="salary"><span>${owned?'持仓成本':'当赛季年薪'}</span><span>${money(owned?p.cost:p.salaryUsd)}</span></div><div class="price" title="${p.price===null?'报价待核实':exact(p.price)}">${money(p.price)} <small>${owned?'当地卖价':'当地报价'}</small></div><div class="trade-bottom"><span class="cost ${owned&&profit!==null?tone(profit):''}">${owned&&profit!==null?signed(profit):delta!==null?'较年薪 '+(delta>=0?'+':'')+delta.toFixed(1)+'%':'合同待核实'}</span><button class="${owned?'':'primary'}" data-action="${owned?'sell':'buy'}" data-player="${esc(p.id)}" ${p.price===null||(!owned&&(g.cash<p.price||g.holdings.length>=5))?'disabled':''}>${owned?'卖出':g.cash<p.price?'资金不足':g.holdings.length>=5?'仓库已满':'买入'}</button></div></article>`;}
function market(v){const owned=tab==='warehouse',list=(owned?v.holdings:v.market).filter(p=>(position==='ALL'||p.position===position)&&p.name.toLowerCase().includes(search.toLowerCase()));return `<div class="section-head"><div><h3>${owned?'你的球员仓库':'寻找下一笔交易'}</h3><p class="muted">${owned?'卖给当前球队，立即结算差价':'全队挂牌 · 当天报价固定'}</p></div><label class="sr-only" for="search">搜索球员</label><input class="search" id="search" type="search" placeholder="搜索球员姓名" value="${esc(search)}"></div><div class="filters">${[['ALL','全部'],['G','后卫'],['F','前锋'],['C','中锋']].map(([id,name])=>`<button data-position="${id}" class="${position===id?'active':''}">${name}</button>`).join('')}<span class="muted" style="margin-left:auto">${list.length}名球员</span></div>${list.length?`<div class="grid">${list.sort((a,b)=>(b.price??-1)-(a.price??-1)).map(p=>playerCard(p,owned)).join('')}</div>`:`<div class="empty"><h3>${owned?'仓库还是空的':'没有匹配球员'}</h3><p>${owned?'先在当地市场买入，再前往另一支球队寻找买家。':'试试其他姓名或位置。'}</p></div>`}`;}
function map(v){return `<div class="section-head"><div><h3>下一站，去哪里？</h3><p class="muted">移动消耗一天。未访问球队的最新报价未知。</p></div></div>${g.day===30?'<div class="warning">已经到第30天。仍可在当前球队买卖，完成后结算本局。</div>':''}<div class="grid">${v.teams.map(t=>`<article class="card team-card"><div class="team-heading"><div class="team-code" style="--team-color:${esc(t.color)}">${esc(t.abbr)}</div><div><h3>${esc(t.name)}</h3><span class="muted">${t.current?'你在这里':t.history?'已访问':'尚未访问'}</span></div></div><div class="history">${t.history?'历史报价：'+esc(t.history.date):'价格未知 · 需要亲自到访'}</div>${t.history?`<details><summary>查看历史报价</summary><div class="history-table">${s.players.filter(p=>t.history.prices[p.id]!==null).map(p=>`<span>${esc(p.name)}</span><strong>${money(t.history.prices[p.id])}</strong>`).join('')}</div><p class="muted">历史访问时对全部球员的报价，不能保证当前仍相同或仍属该队。</p></details>`:''}<button data-action="move" data-team="${esc(t.id)}" ${t.current||g.day===30?'disabled':''}>${t.current?'当前球队':'前往 '+esc(t.name)+' →'}</button></article>`).join('')}</div>`;}
function news(v){return `<div class="section-head"><div><h3>联盟资讯</h3><p class="muted">截至 ${esc(v.date)} 的真实记录 · 不提供价格预测</p></div></div><div class="news-layout"><section>${v.news.length?v.news.map(n=>{const src=source(n.sourceId);return `<article class="news-item"><div class="meta"><span>${esc(n.date)} · ${n.type==='result'?'比赛结果':'新闻'}</span>${src?`<a href="${esc(src.url)}" target="_blank" rel="noopener">来源 ↗</a>`:''}</div><h3>${esc(n.title)}</h3><p>${esc(n.summary)}</p></article>`;}).join(''):'<div class="empty">今天暂无已收录资讯</div>'}</section><aside class="card"><h3>当天球员表现</h3><p class="muted">${v.performances.length}条技术统计</p>${v.performances.length?v.performances.slice(0,40).map(f=>`<div class="performance"><div>${esc(playerName(f.playerId))}<small>${esc(f.payload.opponent)}</small></div><div>${f.payload.points}分 / ${f.payload.rebounds}板 / ${f.payload.assists}助</div></div>`).join(''):'<p class="muted" style="margin-top:20px">当天暂无已收录比赛表现。</p>'}</aside></div>`;}
function results(){const r=settle(s,g);root.innerHTML=`<section class="results"><span class="eyebrow">YOUR CAREER, YOUR SCORE</span><h1>这一局，你的眼光值多少？</h1><p class="muted">第 ${g.day} 天结束 · 现金与持仓统一参考价值结算</p><div class="big-money">${exact(r.totalAssets)}</div><p class="${tone(r.totalProfit)}">总收益 ${signed(r.totalProfit)} · ${(r.totalProfit/15000000*100).toFixed(2)}%</p><div class="stats" style="margin-top:30px"><div class="stat"><label>剩余现金</label><strong>${money(r.cash)}</strong></div><div class="stat"><label>持仓参考价值</label><strong>${money(r.inventoryValue)}</strong></div><div class="stat"><label>已实现盈亏</label><strong class="${tone(r.realizedProfit)}">${signed(r.realizedProfit)}</strong></div><div class="stat"><label>持仓浮动盈亏</label><strong class="${tone(r.unrealizedProfit)}">${signed(r.unrealizedProfit)}</strong></div></div><p class="muted">完成 ${g.transactions.length} 笔买卖 · 持仓 ${g.holdings.length} 人<br>结算持仓使用统一参考价值，不含球队偏好。</p><button class="primary" data-restart>再经营一次 →</button></section>`;}
function render(){if(g.ended){results();if(saveWarning)root.insertAdjacentHTML('afterbegin',`<div id="save-warning" class="warning" role="alert">${esc(saveWarning)}</div>`);return;}const v=buildView(s,g,tab);root.innerHTML=(saveWarning?`<div id="save-warning" class="warning" role="alert">${esc(saveWarning)}</div>`:'')+header(v)+(tab==='map'?map(v):tab==='news'?news(v):market(v))+`<div class="endbar"><p class="muted">持仓参考价值 ${money(v.summary.inventoryValue)}<br>总资产 ${money(v.summary.totalAssets)}</p><div><button data-restart>重新开局</button> <button data-action="finish" class="${g.day===30?'primary':''}">${g.day===30?'结算本局':'提前结束本局'}</button></div></div>`;}
root.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b||b.disabled)return;
 if(b.hasAttribute('data-start')){if((savedGame||preserveSave)&&!confirm('新开局将覆盖原存档，是否继续？'))return;g=createGame(s,document.querySelector('#start-team').value);preserveSave=false;tab='market';position='ALL';search='';persist();render();return;}
 if(b.hasAttribute('data-resume')){g=savedGame;render();return;}
 if(b.hasAttribute('data-restart')){if(!confirm('结束当前进度并重新开局？'))return;savedGame=null;setup();return;}
 if(b.dataset.tab){tab=b.dataset.tab;position='ALL';search='';render();return;}
 if(b.dataset.position){position=b.dataset.position;render();return;}
 if(b.dataset.action){if(b.dataset.action==='finish'&&!confirm('结算当前现金与持仓并结束本局？'))return;const result=act(s,g,{type:b.dataset.action,playerId:b.dataset.player,teamId:b.dataset.team});if(!result.ok){toast(result.error);return;}g=result.state;persist();render();if(b.dataset.action==='move')toast('到达 '+s.teams.find(t=>t.id===g.teamId).name+' · 第'+g.day+'天');else if(b.dataset.action!=='finish')toast(b.dataset.action==='buy'?'买入成功，球员已进入仓库':'卖出成功，资金已到账');}
});
root.addEventListener('input',e=>{if(e.target.id==='search'){const at=e.target.selectionStart;search=e.target.value;render();const input=document.querySelector('#search');input.focus();try{input.setSelectionRange(at,at);}catch{}}});
document.querySelector('#help').addEventListener('click',()=>document.querySelector('#help-dialog').showModal());document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>document.querySelector('#help-dialog').close()));
try{const response=await fetch(new URL('../data/snapshot.json',import.meta.url));if(!response.ok)throw new Error('数据加载失败 HTTP '+response.status);s=await response.json();const errors=validateSnapshot(s,{allowIncomplete:true});if(errors.length)throw new Error('数据校验失败：'+errors.slice(0,3).join('；'));let loaded;try{loaded=loadGame(localStorage,s);}catch{loaded={state:null,warning:'浏览器存储不可用，进度只保留在本页。'};}savedGame=loaded.state;preserveSave=!!loaded.warning;setup(loaded.warning);}catch(error){root.innerHTML=`<section class="loading"><h1>市场暂未打开</h1><p>${esc(error.message)}</p><p class="muted">请通过本地HTTP服务运行，或检查部署的数据文件。</p><button onclick="location.reload()">重新加载</button></section>`;}
